### ISSUE TITLE
setup.bat failed to work.

### ISSUE THREAD

**Issue by AlternativeLua** [TheCherno/WalnutAppTemplate#8]
![image](https://user-images.githubusercontent.com/83465599/224511128-9eca5694-c298-454e-a583-495b08cf0fee.png)
I am getting this message ``The system cannot find the path specified`.  The file dir is in the d drive. I cloned the template.

**Comment by NameTakenBonk** [comment]
Fixed

**Comment by AlternativeLua** [comment]
Fixed by doing a --recursive clone
